org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.configuration-cache=true

# Versions can be found at https://parchmentmc.org/docs/getting-started
neoForge.parchment.minecraftVersion=1.21.1
neoForge.parchment.mappingsVersion=2024.11.17

# Mod Info
mod_version=1.6.2
modid=umbral_skies
group_name=us.drullk.umbralskies

# Minecraft
base_minecraft_version=1.21
minecraft_version=1.21.1

# NeoForge: https://projects.neoforged.net/neoforged/neoforge
neo_version=21.1.209
mdg_version=2.0.76

## Dependencies
twilight_version=4.8.3260
aether_version=1.21.1-1.5.10-neoforge
nitrogen_version=1.21.1-1.1.25-neoforge
cumulus_version=1.21.1-2.0.8-neoforge
accessories_version=1.1.0-beta.49
endec_version=0.1.5.1
owo_version=0.12.15.1-beta.6+1.21
cloth_config_version=15.0.140